[package]
name = "ray_tracing_in_one_weekend"
version = "0.1.0"
edition = "2021"
authors = ["Seiichi Ariga <seiichi.ariga@gmail.com>"]
rust-version = "1.69.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.2"
